config/routes.rb
Rails.application.routes.draw do
  # First user story
  # A page with a form, where User can type their question and submit it
  get '/ask', to: 'questions#ask', as: :ask

  # Second user story
  # A page where in the controller, we will code the logic
  # of what the coach's answer is supposed to be
  # And then display that answer on the this page
  get '/answer', to: 'questions#answer', as: :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def ask
  end

  def answer
    # params is a Hash ==> { "question" => "This is whatever the user is writing"}
    puts "WHAT'S THE QUESTION? #{params[:question]}"
    @answer = get_coach_answer(params[:question])
  end

  private
  
  def get_coach_answer(question)
    ## BELOW HERE is the Stupid Coach's logic:
    # 1. If the message is I am going to work, the coach will answer Great!
    # 2. If the message has a question mark ? at the end, the coach will answer Silly question, get dressed and go to work!.
    # 3. Otherwise the coach will answer I don't care, get dressed and go to work!
    if question.downcase == 'i am going to work'
      "Great!"
    elsif question[-1] == '?'
      "Silly question, get dressed and go to work!"
    else
      "I don't care, get dressed and go to work!"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching1361</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>This is your coach's answer</h1>

<div>
  <p>
    <%= params[:question] %>
  </p>
  <p>
    -- You
  </p>
</div>

<div>
  <p>
    <%= @answer %>
  </p>
  <p>
    -- Your Coach
  </p>
</div>

<div>
  <%= link_to 'Ask again!', ask_path %>
</div>

app/views/questions/ask.html.erb
<h1>Ask your question to your coach</h1>

<div class="w-50">
  <form action="/answer" method="get" data-turbo="false">
    <div class="input-group mb-3">
      <input type="text" name="question" class="form-control" placeholder="Ask your question here..">
      <input type="submit" value="Ask!" class="btn btn-outline-secondary" type="button" id="button-addon2">
    </div>
  </form>
</div>